# Generated by Django 5.2.17 on 2026-09-03 14:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemple: 2026-2027', max_length=9, unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom identificatiu de la família', max_length=160)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('monthly_email_enabled', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_groups', to='cafeteria.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(default='Excursió', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='cafeteria.coursegroup')),
            ],
            options={
                'ordering': ['date', 'course_group'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_outdated', models.BooleanField(default=False)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Exemple: mare, pare, tutor legal', max_length=80)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cafeteria.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gestor de menjador'), ('tutor', 'Tutor')], default='tutor', max_length=16)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='cafeteria.family')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_cutoff', models.TimeField(blank=True, help_text="Sense valor: no s'envia cap informe automàtic.", null=True)),
                ('monthly_preparation_day', models.PositiveSmallIntegerField(default=1)),
                ('monthly_preparation_hour', models.TimeField(default='08:00')),
                ('daily_reports_enabled', models.BooleanField(default=False)),
                ('monthly_statements_enabled', models.BooleanField(default=True)),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_settings', to='cafeteria.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_recipients', to='cafeteria.mealsettings')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('prepared', 'Preparat'), ('closed', 'Tancat'), ('sent', 'Enviat')], default='prepared', max_length=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_statements', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='cafeteria.family')),
            ],
            options={
                'ordering': ['-year', '-month', 'family__name'],
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship', models.BooleanField(default=False)),
                ('meal_plan', models.CharField(choices=[('fixed', 'Fix'), ('sporadic', 'Esporàdic')], max_length=12)),
                ('effective_from', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', 'scholarship', 'meal_plan'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_service_day', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_days', to='cafeteria.academicyear')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=120)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_notes', models.TextField(blank=True)),
                ('dietary_notes', models.TextField(blank=True)),
                ('is_scholarship', models.BooleanField(default=False, verbose_name='Alumne becat')),
                ('meal_plan', models.CharField(choices=[('fixed', 'Fix'), ('sporadic', 'Esporàdic')], default='fixed', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='cafeteria.coursegroup')),
                ('default_diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='cafeteria.diet')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='cafeteria.family')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('diet_name', models.CharField(blank=True, max_length=80)),
                ('meal_plan', models.CharField(choices=[('fixed', 'Fix'), ('sporadic', 'Esporàdic')], max_length=12)),
                ('scholarship', models.BooleanField(default=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cafeteria.monthlystatement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_lines', to='cafeteria.student')),
            ],
            options={
                'ordering': ['service_date', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='MealBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('diet_name', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Anul·lada')], default='active', max_length=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='cafeteria.diet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bookings', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cafeteria.student')),
            ],
            options={
                'ordering': ['date', 'student__first_name', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Català'), ('es', 'Castellano')], default='ca', max_length=2)),
                ('receive_operational_emails', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='coursegroup',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_course_group_per_year'),
        ),
        migrations.AddConstraint(
            model_name='courseclosure',
            constraint=models.UniqueConstraint(fields=('course_group', 'date'), name='unique_course_closure'),
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.UniqueConstraint(fields=('family', 'user'), name='unique_family_membership'),
        ),
        migrations.AddConstraint(
            model_name='dailyreportrecipient',
            constraint=models.UniqueConstraint(fields=('settings', 'email'), name='unique_daily_recipient'),
        ),
        migrations.AddConstraint(
            model_name='monthlystatement',
            constraint=models.UniqueConstraint(fields=('family', 'year', 'month'), name='unique_family_monthly_statement'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.UniqueConstraint(fields=('scholarship', 'meal_plan', 'effective_from'), name='unique_price_effectivity'),
        ),
        migrations.AddConstraint(
            model_name='serviceday',
            constraint=models.UniqueConstraint(fields=('academic_year', 'date'), name='unique_service_day'),
        ),
        migrations.AddConstraint(
            model_name='statementline',
            constraint=models.UniqueConstraint(fields=('statement', 'student', 'service_date'), name='unique_statement_line'),
        ),
        migrations.AddConstraint(
            model_name='mealbooking',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_meal_booking'),
        ),
    ]
