# Generated by Django 5.2.17 on 2026-09-03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def add_default_diet(apps, schema_editor):
    Diet = apps.get_model("cafeteria", "Diet")
    Student = apps.get_model("cafeteria", "Student")
    if not Student.objects.filter(default_diet__isnull=True).exists():
        return
    diet, _created = Diet.objects.get_or_create(
        name="Ordinària",
        defaults={"description": "Dieta habitual", "active": True, "sort_order": 0},
    )
    Student.objects.filter(default_diet__isnull=True).update(default_diet=diet)


class Migration(migrations.Migration):

    dependencies = [
        ("cafeteria", "0002_familyimportbatch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("school_menu_url", models.URLField(default="https://agora.xtec.cat/esc-mariapages-ordis/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_portal_settings", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Configuració del portal"},
        ),
        migrations.RunPython(add_default_diet, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="student",
            name="default_diet",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="students", to="cafeteria.diet"),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_scholarship",
            field=models.BooleanField(default=False, verbose_name="Ajut de menjador"),
        ),
        migrations.AlterField(
            model_name="familymembership",
            name="label",
            field=models.CharField(blank=True, help_text="Exemple: persona tutora o contacte principal", max_length=80),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(choices=[("admin", "Administració"), ("manager", "Gestió de menjador"), ("tutor", "Persona tutora"), ("teacher", "Personal docent")], default="tutor", max_length=16),
        ),
        migrations.AddField(
            model_name="mealbooking",
            name="meal_type",
            field=models.CharField(choices=[("regular", "Menú convencional"), ("packed_lunch", "Carmanyola")], default="regular", max_length=16),
        ),
        migrations.AddField(
            model_name="statementline",
            name="meal_type",
            field=models.CharField(choices=[("regular", "Menú convencional"), ("packed_lunch", "Carmanyola")], default="regular", max_length=16),
        ),
        migrations.CreateModel(
            name="TeacherMealProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("meal_plan", models.CharField(choices=[("fixed", "Fix"), ("sporadic", "Esporàdic")], default="sporadic", max_length=12)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default_diet", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teacher_profiles", to="cafeteria.diet")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="teacher_meal_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["user__first_name", "user__last_name", "user__email"]},
        ),
        migrations.CreateModel(
            name="TeacherMonthlyStatement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("status", models.CharField(choices=[("prepared", "Preparat"), ("closed", "Tancat"), ("sent", "Enviat")], default="prepared", max_length=12)),
                ("total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=9)),
                ("prepared_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="closed_teacher_statements", to=settings.AUTH_USER_MODEL)),
                ("teacher", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="statements", to="cafeteria.teachermealprofile")),
            ],
            options={"ordering": ["-year", "-month", "teacher__user__first_name"]},
        ),
        migrations.CreateModel(
            name="TeacherMealBooking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("diet_name", models.CharField(blank=True, max_length=80)),
                ("meal_type", models.CharField(choices=[("regular", "Menú convencional"), ("packed_lunch", "Carmanyola")], default="regular", max_length=16)),
                ("status", models.CharField(choices=[("active", "Activa"), ("cancelled", "Anul·lada")], default="active", max_length=12)),
                ("unit_price", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("override_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_teacher_bookings", to=settings.AUTH_USER_MODEL)),
                ("diet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="teacher_bookings", to="cafeteria.diet")),
                ("teacher", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bookings", to="cafeteria.teachermealprofile")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_teacher_bookings", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["date", "teacher__user__first_name", "teacher__user__last_name"]},
        ),
        migrations.CreateModel(
            name="TeacherStatementLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("service_date", models.DateField()),
                ("diet_name", models.CharField(blank=True, max_length=80)),
                ("meal_type", models.CharField(choices=[("regular", "Menú convencional"), ("packed_lunch", "Carmanyola")], default="regular", max_length=16)),
                ("meal_plan", models.CharField(choices=[("fixed", "Fix"), ("sporadic", "Esporàdic")], max_length=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("statement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="cafeteria.teachermonthlystatement")),
            ],
            options={"ordering": ["service_date"]},
        ),
        migrations.AddConstraint(
            model_name="teachermonthlystatement",
            constraint=models.UniqueConstraint(fields=("teacher", "year", "month"), name="unique_teacher_monthly_statement"),
        ),
        migrations.AddConstraint(
            model_name="teachermealbooking",
            constraint=models.UniqueConstraint(fields=("teacher", "date"), name="unique_teacher_meal_booking"),
        ),
        migrations.AddConstraint(
            model_name="teacherstatementline",
            constraint=models.UniqueConstraint(fields=("statement", "service_date"), name="unique_teacher_statement_line"),
        ),
    ]
