# Generated by Django 5.2.17 on 2026-09-03

from django.db import migrations, models
from django.db.models import F


def keep_existing_report_schedule(apps, schema_editor):
    MealSettings = apps.get_model("cafeteria", "MealSettings")
    MealSettings.objects.filter(
        daily_report_send_time__isnull=True,
        daily_cutoff__isnull=False,
    ).update(daily_report_send_time=F("daily_cutoff"))


class Migration(migrations.Migration):

    dependencies = [("cafeteria", "0003_portal_menu_teachers_and_packed_lunch")]

    operations = [
        migrations.AddField(
            model_name="mealsettings",
            name="daily_report_send_time",
            field=models.TimeField(blank=True, help_text="Sense valor: no s'envia cap informe diari automàtic.", null=True),
        ),
        migrations.RunPython(keep_existing_report_schedule, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="mealsettings",
            name="daily_cutoff",
            field=models.TimeField(blank=True, help_text="Sense valor: les famílies poden modificar reserves fins al final del dia.", null=True),
        ),
    ]
