# Generated by Django 5.2.17 on 2026-09-04

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_fee_settings_for_existing_years(apps, schema_editor):
    AcademicYear = apps.get_model("cafeteria", "AcademicYear")
    AfaFeeSettings = apps.get_model("cafeteria", "AfaFeeSettings")
    for academic_year in AcademicYear.objects.all():
        AfaFeeSettings.objects.get_or_create(academic_year=academic_year)


class Migration(migrations.Migration):

    dependencies = [
        ("cafeteria", "0004_separate_daily_report_send_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicHoliday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("holiday_type", models.CharField(choices=[("general", "Festiu general"), ("local", "Festiu local"), ("school", "Festiu de centre")], default="general", max_length=12)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="holidays", to="cafeteria.academicyear")),
            ],
            options={"ordering": ["starts_on", "ends_on", "title"]},
        ),
        migrations.CreateModel(
            name="AfaFeeSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=7)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academic_year", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="afa_fee_settings", to="cafeteria.academicyear")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_afa_fee_settings", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="AfaMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pendent de cobrament"), ("paid", "Pagada"), ("exempt", "Exempta")], default="pending", max_length=12)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=7)),
                ("paid_on", models.DateField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, choices=[("transfer", "Transferència"), ("cash", "Efectiu"), ("card", "Targeta"), ("other", "Altres")], max_length=16)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="afa_memberships", to="cafeteria.academicyear")),
                ("family", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="afa_memberships", to="cafeteria.family")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_afa_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-academic_year__starts_on", "family__name"],
                "constraints": [models.UniqueConstraint(fields=("family", "academic_year"), name="unique_afa_membership_per_year")],
            },
        ),
        migrations.RunPython(create_fee_settings_for_existing_years, migrations.RunPython.noop),
    ]
