# Generated by Django 5.2.17 on 2026-09-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cafeteria", "0005_academicholiday_afafeesettings_afamembership")]

    operations = [
        migrations.CreateModel(
            name="AcademicIntensivePeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="Jornada intensiva", max_length=160)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="intensive_periods", to="cafeteria.academicyear")),
            ],
            options={"ordering": ["starts_on", "ends_on", "title"]},
        ),
    ]
