# Generated by Django 5.2.17 on 2026-09-04

import apps.cafeteria.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_economic_defaults(apps, schema_editor):
    FinancialAccount = apps.get_model("cafeteria", "FinancialAccount")
    EconomicCategory = apps.get_model("cafeteria", "EconomicCategory")
    EconomicSettings = apps.get_model("cafeteria", "EconomicSettings")
    FinancialAccount.objects.get_or_create(name="Compte bancari AFA", defaults={"account_type": "bank"})
    FinancialAccount.objects.get_or_create(name="Efectiu", defaults={"account_type": "cash"})
    categories = [
        ("Quotes AFA", "income"), ("Subvencions i ajuts", "income"), ("Activitats", "income"),
        ("Donacions", "income"), ("Altres ingressos", "income"),
        ("Activitats", "expense"), ("Material", "expense"), ("Assegurances i gestoria", "expense"),
        ("Comunicació", "expense"), ("Serveis", "expense"), ("Comissions bancàries", "expense"),
        ("Ajuts", "expense"), ("Altres despeses", "expense"),
    ]
    for order, (name, entry_type) in enumerate(categories):
        EconomicCategory.objects.get_or_create(name=name, entry_type=entry_type, defaults={"sort_order": order})
    EconomicSettings.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ("cafeteria", "0007_userprofile_navigation_state_dashboard_widgets_and_academicnotice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("account_type", models.CharField(choices=[("bank", "Compte bancari"), ("cash", "Efectiu"), ("other", "Altres")], default="bank", max_length=12)),
                ("opening_balance", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("opening_balance_date", models.DateField(default=django.utils.timezone.localdate)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(model_name="userprofile", name="can_submit_expenses", field=models.BooleanField(default=False)),
        migrations.CreateModel(
            name="EconomicCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("entry_type", models.CharField(choices=[("income", "Ingrés"), ("expense", "Despesa")], max_length=10)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["entry_type", "sort_order", "name"], "constraints": [models.UniqueConstraint(fields=("name", "entry_type"), name="unique_economic_category_type")]},
        ),
        migrations.CreateModel(
            name="EconomicEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_type", models.CharField(choices=[("income", "Ingrés"), ("expense", "Despesa")], max_length=10)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("concept", models.CharField(max_length=180)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("review_status", models.CharField(choices=[("submitted", "Pendent de revisar"), ("approved", "Aprovada"), ("rejected", "Rebutjada"), ("withdrawn", "Retirada")], default="approved", max_length=12)),
                ("payment_status", models.CharField(choices=[("pending", "Pendent de pagament"), ("paid", "Pagada")], default="paid", max_length=12)),
                ("paid_on", models.DateField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="cafeteria.economiccategory")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_economic_entries", to=settings.AUTH_USER_MODEL)),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="submitted_economic_entries", to=settings.AUTH_USER_MODEL)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="cafeteria.financialaccount")),
            ],
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="EconomicAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=apps.cafeteria.models.economic_attachment_path)),
                ("original_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="cafeteria.economicentry")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="EconomicSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allow_all_users_expense_submissions", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_economic_settings", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(seed_economic_defaults, migrations.RunPython.noop),
    ]
