# Generated by Django 5.2.17 on 2026-09-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0008_financialaccount_userprofile_can_submit_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ca', 'Català'), ('es', 'Castellà')], default='ca', max_length=2),
        ),
    ]
