# Generated by Django 5.2.17 on 2026-09-06 09:10

import apps.cafeteria.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0010_remove_meal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembership',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymembership',
            name='onboarding_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='allergy_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='allergy_document',
            field=models.FileField(blank=True, upload_to=apps.cafeteria.models.allergy_document_path),
        ),
        migrations.AddField(
            model_name='student',
            name='allergy_document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='allergy_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='allergy_review_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendent de validar'), ('approved', 'Validada'), ('rejected', 'Rebutjada')], max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='allergy_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='allergy_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_allergies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='allergy_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='student',
            name='has_allergy',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
