# Generated by Django 5.2.17 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafeteria", "0012_userprofile_family_booking_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalsettings",
            name="allow_family_student_creation",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="family",
            name="address",
        ),
        migrations.RemoveField(
            model_name="family",
            name="billing_email",
        ),
    ]
