# Generated by Django 5.2.17 on 2026-09-06 15:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def assign_private_ids(apps, schema_editor):
    student_model = apps.get_model('cafeteria', 'Student')
    for student in student_model.objects.using(schema_editor.connection.alias).all().iterator():
        student.privacy_id = uuid.uuid4()
        student.save(update_fields=['privacy_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0014_alter_afafeesettings_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.UUIDField(db_index=True)),
                ('category', models.CharField(choices=[('health', 'Salut, després de la baixa o rectificació'), ('operational', 'Dades operatives, després de la baixa'), ('accounting', 'Comptabilitat, després del tancament'), ('audit', 'Registres de seguretat, des de la creació'), ('rights', 'Sol·licituds de drets, després de resoldre-les'), ('consent', 'Consentiments, després de la retirada o baixa')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destroy_after', models.DateTimeField()),
                ('legal_hold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestrictionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.UUIDField()),
                ('category', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destroy_after', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailyreportrecipient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='inactive_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='kitchen_instructions',
            field=models.TextField(blank=True, verbose_name='Instruccions alimentàries per a cuina'),
        ),
        migrations.AddField(
            model_name='student',
            name='privacy_id',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(assign_private_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student', name='privacy_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='safety_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Administració'), ('manager', 'Gestió de menjador'), ('tutor', 'Persona tutora'), ('teacher', 'Personal docent'), ('kitchen', 'Cuina'), ('health_reviewer', 'Revisió documental de salut'), ('privacy', 'Responsable de privacitat')], default='tutor', max_length=16),
        ),
        migrations.CreateModel(
            name='BackupCustody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('access', 'Accés / portabilitat'), ('rectify', 'Rectificació'), ('erase', 'Supressió'), ('restrict', 'Limitació / oposició')], max_length=12, verbose_name='Dret que vols exercir')),
                ('message', models.TextField(max_length=3000, verbose_name='Detall de la sol·licitud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True)),
                ('export_file', models.FileField(blank=True, upload_to='privacy_exports/')),
                ('export_expires_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_data_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafeteria.student', verbose_name='Infant, si escau')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, unique=True, verbose_name='Versió')),
                ('controller', models.CharField(max_length=200, verbose_name="Nom legal de l'AFA")),
                ('tax_id', models.CharField(max_length=32, verbose_name='NIF')),
                ('address', models.CharField(max_length=255, verbose_name='Adreça legal')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contacte de privacitat')),
                ('text_ca', models.TextField(verbose_name='Política en català')),
                ('text_es', models.TextField(verbose_name='Política en castellà')),
                ('health_text_ca', models.TextField(verbose_name='Consentiment explícit de salut en català')),
                ('health_text_es', models.TextField(verbose_name='Consentiment explícit de salut en castellà')),
                ('contracts_verified', models.BooleanField(default=False, verbose_name='Contractes i transferències verificats')),
                ('assessment_approved', models.BooleanField(default=False, verbose_name="Avaluació d'impacte i bases jurídiques validades")),
                ('recovery_verified', models.BooleanField(default=False, verbose_name='Restauració i custòdia de claus verificades')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('authority_confirmed', models.BooleanField(default=False)),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_consents', to='cafeteria.student')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafeteria.privacynotice')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=128)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetentionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('health', 'Salut, després de la baixa o rectificació'), ('operational', 'Dades operatives, després de la baixa'), ('accounting', 'Comptabilitat, després del tancament'), ('audit', 'Registres de seguretat, des de la creació'), ('rights', 'Sol·licituds de drets, després de resoldre-les'), ('consent', 'Consentiments, després de la retirada o baixa')], max_length=20, unique=True, verbose_name='Categoria')),
                ('days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36500)], verbose_name='Dies de conservació')),
                ('justification', models.TextField(verbose_name='Justificació i norma aplicable')),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
