# Generated by Django 5.2.17 on 2026-09-06 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0015_blockeddata_restrictionevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='default_diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='cafeteria.diet'),
        ),
    ]
