# Generated by Django 5.2.17 on 2026-09-06 20:42

from django.db import migrations, models


def remove_obsolete_role_grants(apps, schema_editor):
    group_model = apps.get_model("auth", "Group")
    group_model.objects.filter(name__in=("health_reviewer", "privacy")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cafeteria", "0018_case_insensitive_report_recipient_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administració"),
                    ("manager", "Gestió de menjador"),
                    ("tutor", "Persona tutora"),
                    ("teacher", "Personal docent"),
                    ("kitchen", "Cuina"),
                ],
                default="tutor",
                max_length=16,
            ),
        ),
        migrations.DeleteModel(
            name="RecoveryCode",
        ),
        migrations.RunPython(remove_obsolete_role_grants, migrations.RunPython.noop),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS django_otp_totpdevice",
            migrations.RunSQL.noop,
        ),
    ]
