from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

app_name = "cafeteria"

urlpatterns = [
    path("health/", views.healthcheck, name="healthcheck"),
    path("", views.dashboard, name="dashboard"),
    path("comptes/entrada/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("comptes/sortida/", auth_views.LogoutView.as_view(), name="logout"),
    path("comptes/idioma/", views.set_language, name="set_language"),
    path("comptes/contrasenya/", views.password_reset_request, name="password_reset"),
    path("comptes/contrasenya/enviada/", auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_done"),
    path("comptes/contrasenya/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="registration/password_reset_confirm.html",
        success_url=reverse_lazy("cafeteria:password_reset_complete"),
    ), name="password_reset_confirm"),
    path("comptes/contrasenya/feta/", auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"), name="password_reset_complete"),
    path("families/<int:family_id>/menjador/", views.family_calendar, name="family_calendar"),
    path("families/<int:family_id>/menjador/actualitza/", views.bulk_booking, name="bulk_booking"),
    path("families/<int:family_id>/menjador/actualitza-tots/", views.family_bulk_booking, name="family_bulk_booking"),
    path("personal/menjador/", views.teacher_calendar, name="teacher_calendar"),
    path("personal/menjador/actualitza/", views.teacher_bulk_booking, name="teacher_bulk_booking"),
    path("alumnes/<int:student_id>/edita/", views.student_edit, name="student_edit"),
    path("invitacions/nova/", views.invitation_create, name="invitation_create"),
    path("invitacions/<str:token>/", views.invitation_accept, name="invitation_accept"),
    path("gestio/tarifes/", views.price_rules, name="price_rules"),
    path("gestio/informes-diaris/", views.daily_reports, name="daily_reports"),
    path("gestio/informes-diaris/<str:service_date>/envia/", views.daily_report_send, name="daily_report_send"),
    path("gestio/planificacio-mensual/", views.monthly_planning, name="monthly_planning"),
    path("resums/", views.monthly_statements, name="monthly_statements"),
    path("resums/prepara/", views.statement_prepare, name="statement_prepare"),
    path("resums/<int:statement_id>/", views.statement_detail, name="statement_detail"),
    path("resums/<int:statement_id>/tanca/", views.statement_close, name="statement_close"),
    path("resums/<int:statement_id>/envia/", views.statement_send, name="statement_send"),
    path("resums/<int:statement_id>/csv/", views.statement_csv, name="statement_csv"),
    path("resums/personal/<int:statement_id>/", views.teacher_statement_detail, name="teacher_statement_detail"),
    path("resums/personal/<int:statement_id>/tanca/", views.teacher_statement_close, name="teacher_statement_close"),
    path("resums/personal/<int:statement_id>/envia/", views.teacher_statement_send, name="teacher_statement_send"),
    path("gestio/auditoria/", views.audit_log, name="audit_log"),
    path("gestio/", views.management_dashboard, name="management_dashboard"),
    path("gestio/persones/", views.people, name="people"),
    path("gestio/comptes/", views.accounts, name="accounts"),
    path("gestio/comptes/<int:user_id>/restableix/", views.account_reset_link, name="account_reset_link"),
    path("gestio/personal/<int:profile_id>/menjador/", views.teacher_profile_edit, name="teacher_profile_edit"),
    path("gestio/families/nova/", views.family_form, name="family_create"),
    path("gestio/families/<int:family_id>/edita/", views.family_form, name="family_edit"),
    path("gestio/alumnes/nou/", views.management_student_form, name="management_student_create"),
    path("gestio/alumnes/<int:student_id>/edita/", views.management_student_form, name="management_student_edit"),
    path("gestio/calendari/", views.school_calendar, name="school_calendar"),
    path("gestio/cursos/nou/", views.academic_year_save, name="academic_year_create"),
    path("gestio/cursos/<int:year_id>/edita/", views.academic_year_save, name="academic_year_edit"),
    path("gestio/cursos/<int:year_id>/dies-lectius/", views.generate_service_days, name="generate_service_days"),
    path("gestio/dies/<str:service_date>/", views.service_day_toggle, name="service_day_toggle"),
    path("gestio/grups/nou/", views.course_group_save, name="course_group_create"),
    path("gestio/grups/<int:group_id>/edita/", views.course_group_save, name="course_group_edit"),
    path("gestio/excursions/nova/", views.course_closure_save, name="course_closure_create"),
    path("gestio/configuracio-menjadors/", views.meal_configuration, name="meal_configuration"),
    path("gestio/enllac-menu/", views.menu_settings, name="menu_settings"),
    path("gestio/importacio/", views.family_import, name="family_import"),
    path("gestio/importacio/plantilla/", views.family_import_template, name="family_import_template"),
    path("gestio/importacio/<int:batch_id>/", views.family_import_preview, name="family_import_preview"),
    path("gestio/importacio/<int:batch_id>/confirma/", views.family_import_confirm, name="family_import_confirm"),
]
